export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const SERVER_CREATED = "SERVER_CREATED";
export const SERVER_FETCHED = "SERVER_FETCHED";
export const SERVER_UPDATED = "SERVER_UPDATED";

export const SET_MEMBER_SERVERS = "SET_MEMBER_SERVERS";
export const SET_SERVER_MEMBERS = "SET_SERVER_MEMBERS";

export const CHANNEL_CREATED = "CHANNEL_CREATED";
export const CHANNEL_FETCHED = "CHANNEL_FETCHED";
export const CHANNEL_UPDATED = "CHANNEL_UPDATED";

export const SET_SERVER_CHANNELS = "SET_SERVER_CHANNELS";
export const SET_DIRECT_CHANNELS = "SET_DIRECT_CHANNELS";

export const MESSAGE_CREATED = "MESSAGE_CREATED";

export const SET_CHANNEL_MESSAGES = "SET_CHANNEL_MESSAGES";
