export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const ADD_SERVER = "ADD_SERVER";

export const SET_MEMBER_SERVERS = "SET_MEMBER_SERVERS";
export const SET_SERVER_MEMBERS = "SET_SERVER_MEMBERS";
