export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const SERVER_CREATED = "SERVER_CREATED";
export const SERVER_FETCHED = "SERVER_FETCHED";
export const SERVER_UPDATED = "SERVER_UPDATED";

export const SET_MEMBER_SERVERS = "SET_MEMBER_SERVERS";
export const SET_SERVER_MEMBERS = "SET_SERVER_MEMBERS";
